import uuid
from typing import Optional


class EntityStore:
    """
    In-memory store for canonical entities.

    This class preserves the existing behavior used by
    the unit tests. Explicit entity IDs remain supported.
    """

    def __init__(self):
        self.entities = {}

    def add_entity(
        self,
        entity: dict
    ) -> str:
        """Add an entity and return its entity ID."""

        if not isinstance(
            entity,
            dict,
        ):
            raise TypeError(
                "entity must be a dictionary"
            )

        entity_id = entity.get(
            "entity_id"
        )

        if not entity_id:
            raise ValueError(
                "entity must contain entity_id"
            )

        self.entities[
            entity_id
        ] = entity

        return entity_id

    def get_entity(
        self,
        entity_id: str
    ) -> Optional[dict]:
        """Return an entity by ID."""

        return self.entities.get(
            entity_id
        )

    def get_all_entities(
        self,
    ) -> list[dict]:
        """Return all stored entities."""

        return list(
            self.entities.values()
        )

    def remove_entity(
        self,
        entity_id: str
    ) -> bool:
        """Remove an entity by ID."""

        if entity_id not in self.entities:
            return False

        del self.entities[
            entity_id
        ]

        return True

    def update_entity(
        self,
        entity_id: str,
        updates: dict
    ) -> dict:
        """Update fields of an existing entity."""

        if entity_id not in self.entities:
            raise KeyError(
                f"Entity not found: {entity_id}"
            )

        if not isinstance(
            updates,
            dict,
        ):
            raise TypeError(
                "updates must be a dictionary"
            )

        self.entities[
            entity_id
        ].update(
            updates
        )

        return self.entities[
            entity_id
        ]

    def merge_entity(
        self,
        canonical_id: str,
        incoming_entity: dict
    ) -> dict:
        """
        Merge information into an existing canonical entity.
        """

        if canonical_id not in self.entities:
            raise KeyError(
                f"Entity not found: {canonical_id}"
            )

        if not isinstance(
            incoming_entity,
            dict,
        ):
            raise TypeError(
                "incoming_entity must be a dictionary"
            )

        canonical_entity = self.entities[
            canonical_id
        ]

        for field, value in incoming_entity.items():

            if field == "entity_id":
                continue

            if value is None:
                continue

            if (
                isinstance(
                    value,
                    str,
                )
                and not value.strip()
            ):
                continue

            if field not in canonical_entity:
                canonical_entity[
                    field
                ] = value
                continue

            existing_value = canonical_entity[
                field
            ]

            if existing_value is None:
                canonical_entity[
                    field
                ] = value

        return canonical_entity

    def clear(self):
        """Remove all entities."""

        self.entities.clear()

    def __len__(self):
        """Return number of entities."""

        return len(
            self.entities
        )


class PersistentEntityStore(EntityStore):
    """
    Neo4j-backed canonical entity store.

    New entities receive globally unique canonical IDs
    generated by UUID4.

    Source-local IDs are preserved separately in
    `source_entity_id`.

    Existing canonical entities are loaded from Neo4j
    when the store starts, allowing identity information
    to survive application restarts.
    """

    def __init__(
        self,
        neo4j_writer,
        load_existing=True,
    ):
        super().__init__()

        if neo4j_writer is None:
            raise ValueError(
                "neo4j_writer is required"
            )

        self.neo4j_writer = neo4j_writer

        if load_existing:
            self.load_from_neo4j()

    @staticmethod
    def generate_canonical_id():
        """
        Generate a globally unique canonical entity ID.
        """

        return (
            "ENTITY_"
            + uuid.uuid4().hex
        )

    def add_entity(
        self,
        entity: dict
    ) -> str:
        """
        Add a new entity using a global canonical ID.

        The incoming source-local ID is preserved as
        `source_entity_id`.
        """

        if not isinstance(
            entity,
            dict,
        ):
            raise TypeError(
                "entity must be a dictionary"
            )

        incoming_entity = dict(
            entity
        )

        source_entity_id = (
            incoming_entity.get(
                "entity_id"
            )
        )

        canonical_id = (
            self.generate_canonical_id()
        )

        incoming_entity[
            "entity_id"
        ] = canonical_id

        if (
            source_entity_id
            and source_entity_id
            != canonical_id
        ):
            incoming_entity[
                "source_entity_id"
            ] = source_entity_id

        self.entities[
            canonical_id
        ] = incoming_entity

        self.neo4j_writer.create_entities(
            [
                incoming_entity
            ]
        )

        return canonical_id

    def load_from_neo4j(self):
        """
        Load existing canonical entities from Neo4j.

        This makes the identity store persistent across
        application restarts.
        """

        self.neo4j_writer.connect()

        query = """
        MATCH (e:Entity)

        RETURN
            e.entity_id AS entity_id,
            e.entity_type AS entity_type,
            e.name AS name,
            e.source AS source,
            e.source_entity_id AS source_entity_id,
            e.confidence AS confidence
        ORDER BY e.entity_id
        """

        with self.neo4j_writer.driver.session() as session:

            result = session.run(
                query
            )

            for record in result:

                entity = {
                    "entity_id": record[
                        "entity_id"
                    ],
                    "entity_type": record[
                        "entity_type"
                    ],
                    "name": record[
                        "name"
                    ],
                    "source": record[
                        "source"
                    ],
                    "confidence": record[
                        "confidence"
                    ],
                }

                source_entity_id = (
                    record[
                        "source_entity_id"
                    ]
                )

                if source_entity_id is not None:
                    entity[
                        "source_entity_id"
                    ] = source_entity_id

                self.entities[
                    entity["entity_id"]
                ] = entity

    def update_entity(
        self,
        entity_id: str,
        updates: dict
    ) -> dict:
        """
        Update a canonical entity in memory and Neo4j.
        """

        entity = super().update_entity(
            entity_id,
            updates,
        )

        self.neo4j_writer.create_entities(
            [
                entity
            ]
        )

        return entity

    def merge_entity(
        self,
        canonical_id: str,
        incoming_entity: dict
    ) -> dict:
        """
        Merge incoming information into the canonical entity
        and persist the result to Neo4j.
        """

        entity = super().merge_entity(
            canonical_id,
            incoming_entity,
        )

        self.neo4j_writer.create_entities(
            [
                entity
            ]
        )

        return entity

    def remove_entity(
        self,
        entity_id: str
    ) -> bool:
        """
        Remove an entity from both memory and Neo4j.
        """

        removed = super().remove_entity(
            entity_id
        )

        if not removed:
            return False

        self.neo4j_writer.connect()

        query = """
        MATCH (
            e:Entity {
                entity_id: $entity_id
            }
        )

        DETACH DELETE e
        """

        with self.neo4j_writer.driver.session() as session:
            session.run(
                query,
                entity_id=entity_id,
            )

        return True

    def clear(self):
        """
        Clear in-memory entities and only the entities known
        to this store from Neo4j.
        """

        entity_ids = list(
            self.entities.keys()
        )

        self.neo4j_writer.connect()

        query = """
        MATCH (e:Entity)

        WHERE e.entity_id IN $entity_ids

        DETACH DELETE e
        """

        with self.neo4j_writer.driver.session() as session:

            if entity_ids:
                session.run(
                    query,
                    entity_ids=entity_ids,
                )

        super().clear()