import { useState, type FormEvent, type ReactNode } from 'react'
import { ArrowLeft, ArrowRight, CheckCircle2, Eye, EyeOff } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { AuthLayout } from '../components/auth/AuthLayout'
import { Alert } from '../components/ui/Alert'
import { Button } from '../components/ui/button'
import { Card, CardContent } from '../components/ui/card'
import { Input } from '../components/ui/input'
import { Label } from '../components/ui/label'
import { mockAuthService } from '../services/auth'

function SimplePage({ title, children, eyebrow }: { title: string; children: ReactNode; eyebrow?: string }) { return <AuthLayout title={title} eyebrow={eyebrow}><Card><CardContent>{children}</CardContent></Card></AuthLayout> }
function BackToLogin() { return <Link className="back-link" to="/login"><ArrowLeft size={15} /> Return to sign in</Link> }

export function ForgotPassword() { const [email, setEmail] = useState(''); const [state, setState] = useState<'idle'|'loading'|'success'|'error'>('idle'); async function submit(event: FormEvent) { event.preventDefault(); if (!/^\S+@\S+\.\S+$/.test(email)) { setState('error'); return } setState('loading'); try { await mockAuthService.requestPasswordReset(email); setState('success') } catch { setState('error') } } return <SimplePage title="Recover access"><p className="page-intro">Enter your work email and we will check whether recovery instructions can be provided.</p>{state === 'success' ? <div className="success-state"><CheckCircle2 size={27} /><strong>Request received</strong><p>If an account is associated with that email address, recovery instructions will be provided.</p><BackToLogin /></div> : <form onSubmit={submit} noValidate><div className="field"><Label htmlFor="recovery-email">Work email</Label><Input id="recovery-email" type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="analyst@agency.org" aria-invalid={state === 'error'} />{state === 'error' && <span className="field-error">Enter a valid email address.</span>}</div><Button className="submit-button" disabled={state === 'loading'}>{state === 'loading' ? 'Sending recovery instructions...' : 'Submit request'} <ArrowRight size={17} /></Button><BackToLogin /></form>}</SimplePage> }

export function ResetPassword() { const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [visible, setVisible] = useState(false); const [message, setMessage] = useState(''); const navigate = useNavigate(); async function submit(event: FormEvent) { event.preventDefault(); if (password.length < 8) return setMessage('Use at least 8 characters for your new password.'); if (password !== confirm) return setMessage('Passwords must match.'); await mockAuthService.resetPassword(password, new URLSearchParams(location.search).get('token') ?? undefined); navigate('/login') } return <SimplePage title="Set a new password" eyebrow="Account recovery"><form onSubmit={submit}><div className="field"><Label htmlFor="new-password">New password</Label><div className="password-wrap"><Input id="new-password" type={visible ? 'text' : 'password'} autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} /><button className="icon-button" type="button" onClick={() => setVisible(!visible)} aria-label={visible ? 'Hide password' : 'Show password'}>{visible ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></div><div className="field"><Label htmlFor="confirm-password">Confirm password</Label><Input id="confirm-password" type={visible ? 'text' : 'password'} autoComplete="new-password" value={confirm} onChange={(event) => setConfirm(event.target.value)} /></div>{message && <Alert className="alert-error">{message}</Alert>}<Button className="submit-button">Update password <ArrowRight size={17} /></Button><BackToLogin /></form></SimplePage> }

export function AccessRequest() { const [sent, setSent] = useState(false); const [form, setForm] = useState({ name: '', organization: '', email: '', reason: '' }); async function submit(event: FormEvent) { event.preventDefault(); await mockAuthService.requestAccess(form); setSent(true) } return <SimplePage title="Request controlled access" eyebrow="Investigator onboarding">{sent ? <div className="success-state"><CheckCircle2 size={27} /><strong>Request submitted</strong><p>This frontend flow is ready for backend submission. Approval and provisioning require backend support.</p><BackToLogin /></div> : <form onSubmit={submit}><div className="field"><Label htmlFor="name">Full name</Label><Input id="name" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></div><div className="field"><Label htmlFor="organization">Organization</Label><Input id="organization" value={form.organization} onChange={(event) => setForm({ ...form, organization: event.target.value })} /></div><div className="field"><Label htmlFor="access-email">Work email</Label><Input id="access-email" required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></div><div className="field"><Label htmlFor="reason">Reason for access</Label><textarea id="reason" required className="input textarea" value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} /></div><Button className="submit-button">Submit request <ArrowRight size={17} /></Button><BackToLogin /></form>}</SimplePage> }

export function SessionExpired() { return <SimplePage title="Your session has expired." eyebrow="Session ended"><p className="page-intro">For your protection, sign in again to continue your investigation.</p><Link className="button submit-button" to="/login">Sign in again <ArrowRight size={17} /></Link></SimplePage> }
export function Unauthorized() { return <SimplePage title="Access unavailable" eyebrow="Authorization boundary"><p className="page-intro">This resource is not currently accessible to your session. Authorization controls will be connected to the backend service.</p><div className="action-row"><Link className="button" to="/dashboard">Return to dashboard</Link><button className="text-button" onClick={() => history.back()}>Go back</button></div></SimplePage> }
