import { useState } from 'react'
import { CheckCircle2, FileCheck2, ScanSearch, XCircle } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { EntityReviewCard } from '@/components/investigation/InvestigationPanels'
import { mockEntityMatches, mockExtractions } from '@/mocks/reviews'

export function ReviewQueues() {
  const [matches, setMatches] = useState(mockEntityMatches)
  const [extractions, setExtractions] = useState(mockExtractions)
  return <div className="page-frame flex-1 overflow-y-auto p-6"><div className="mb-6"><p className="eyebrow">Human-in-the-loop / Demo review queue</p><h1 className="page-title">AI review queues</h1><p className="mt-2 text-sm text-muted-foreground">Review local entity-resolution candidates and extracted relationships before they are treated as analyst-approved.</p></div><Tabs defaultValue="matches"><TabsList><TabsTrigger value="matches"><ScanSearch className="mr-2 h-4 w-4" />Entity resolution ({matches.filter((match) => match.status === 'pending').length})</TabsTrigger><TabsTrigger value="extractions"><FileCheck2 className="mr-2 h-4 w-4" />AI extraction ({extractions.filter((item) => item.status === 'pending').length})</TabsTrigger></TabsList><TabsContent value="matches" className="mt-5 grid max-w-3xl gap-4">{matches.map((match) => match.status === 'pending' ? <EntityReviewCard key={match.id} existing={match.existing} candidate={match.candidate} confidence={match.confidence} signals={match.signals} onDecision={(decision) => setMatches((current) => current.map((item) => item.id === match.id ? { ...item, status: decision === 'approved' ? 'approved' : decision === 'rejected' ? 'rejected' : 'pending' } : item))} /> : <Card key={match.id}><CardContent className="flex items-center gap-3 p-5"><CheckCircle2 className="h-5 w-5 text-emerald-400" /><span>{match.existing} / {match.candidate}</span><Badge className="ml-auto">{match.status}</Badge></CardContent></Card>)}</TabsContent><TabsContent value="extractions" className="mt-5 grid max-w-3xl gap-4">{extractions.map((item) => <Card key={item.id}><CardHeader><div className="flex items-center justify-between"><CardTitle className="text-base">{item.subject}</CardTitle><Badge variant={item.kind === 'relationship' ? 'secondary' : 'outline'}>{item.kind}</Badge></div></CardHeader><CardContent><p className="text-sm">{item.detail}</p><p className="mt-2 text-xs text-muted-foreground">Source {item.source} · Confidence {Math.round(item.confidence * 100)}%</p><div className="mt-4 flex gap-2"><button className="button" onClick={() => setExtractions((current) => current.map((entry) => entry.id === item.id ? { ...entry, status: 'accepted' } : entry))}><CheckCircle2 className="h-4 w-4" /> Accept</button><button className="button" onClick={() => setExtractions((current) => current.map((entry) => entry.id === item.id ? { ...entry, status: 'rejected' } : entry))}><XCircle className="h-4 w-4" /> Reject</button></div></CardContent></Card>)}</TabsContent></Tabs></div>
}
